services:
  portfolio:
    image: nginx:mainline-alpine3.20
    container_name: portfolio
    restart: unless-stopped
    volumes:
      - ./www/:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=yetanothertool.com
      - VIRTUAL_PORT=8888
      - LETSENCRYPT_HOST=yetanothertool.com
    networks:
      - proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  proxy:
    name: proxy
    external: true
