# Studio Webux S.E.N.C @ 2021

AWSTemplateFormatVersion: 2010-09-09
Description: Webux Lab - IAM

Parameters:
  BucketName:
    Type: String
  HostedZoneId:
    Type: String

Resources:
  Deployment:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: Policy to deploy the frontend application
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "VisualEditor0"
            Effect: "Allow"
            Action:
              - "s3:PutBucketPolicy"
              - "s3:CreateBucket"
              - "s3:ListBucket"
              - "s3:GetBucketPolicy"
            Resource: !Sub "arn:aws:s3:::www.${BucketName}"
          - Sid: "VisualEditor1"
            Effect: "Allow"
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
            Resource: "arn:aws:s3:::www.${BucketName}/*"

          - Sid: CloudFront
            Effect: Allow
            Action:
              - "cloudfront:GetDistribution"
              - "cloudfront:TagResource"
              - "cloudfront:GetInvalidation"
              - "cloudfront:UpdateDistribution"
              - "cloudfront:CreateDistribution"
              - "cloudfront:CreateInvalidation"
              - "cloudfront:UntagResource"
              - "cloudfront:GetCloudFrontOriginAccessIdentityConfig"
              - "cloudfront:CreateCloudFrontOriginAccessIdentity"
              - "cloudfront:GetCloudFrontOriginAccessIdentity"
              - "cloudfront:UpdateCloudFrontOriginAccessIdentity"
            Resource:
              - !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/*"
          - Sid: ACM
            Effect: Allow
            Action:
              - "acm:DescribeCertificate"
              - "acm:GetCertificate"
              - "acm:RenewCertificate"
              - "acm:AddTagsToCertificate"
            Resource:
              - !Sub "arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/*"
          - Sid: Route53
            Effect: Allow
            Action:
              - "route53:ChangeResourceRecordSets"
            Resource:
              - !Sub arn:aws:route53:::hostedzone/${HostedZoneId}
